{{- if and (include "wazuh-operator.installOperator" .) .Values.rbac.create .Values.operator.watchNamespaces }}
{{- $namespaces := .Values.operator.watchNamespaces }}
{{- $fullName := include "wazuh-operator.fullname" . }}
{{- $labels := include "wazuh-operator.labels" . }}
{{- $operatorNamespace := include "wazuh-operator.namespace" . }}
{{- $serviceAccountName := include "wazuh-operator.serviceAccountName" . }}
{{- range $namespace := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName }}-manager-rolebinding
  namespace: {{ $namespace }}
  labels:
    {{- $labels | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccountName }}
  namespace: {{ $operatorNamespace }}
{{- end }}
{{- end }}
