# Comprehensive credentials example for Wazuh Operator
# This sample demonstrates all credential configuration options:
# - Indexer admin credentials (via secretRef)
# - Dashboard API credentials (via defaultApiEndpoint.credentialsSecret)
# - OpenSearchUser with password from secret
# - Default admin user via OpenSearchUser CRD
---
# 1. SECRETS - Create these first
# ================================

# Indexer admin credentials - used for OpenSearch cluster admin
apiVersion: v1
kind: Secret
metadata:
  name: indexer-admin-credentials
  namespace: wazuh
type: Opaque
stringData:
  username: "admin"
  password: "SecureAdminPass123!" # Change this in production!
---
# Dashboard API credentials - used by dashboard to connect to Wazuh Manager API
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-credentials
  namespace: wazuh
type: Opaque
stringData:
  username: "wazuh-wui"
  password: "WazuhApiPass456!" # Change this in production!
---
# Analyst user password
apiVersion: v1
kind: Secret
metadata:
  name: analyst-user-password
  namespace: wazuh
type: Opaque
stringData:
  password: "AnalystPass789!" # Change this in production!
---
# Read-only user password (example with custom key)
apiVersion: v1
kind: Secret
metadata:
  name: readonly-user-credentials
  namespace: wazuh
type: Opaque
stringData:
  user-password: "ReadOnlyPass!" # Using custom key "user-password"

---
# 2. WAZUH CLUSTER - With credential references
# =============================================

apiVersion: resources.wazuh.com/v1alpha1
kind: WazuhCluster
metadata:
  name: wazuh-secure
  namespace: wazuh
  labels:
    environment: production
spec:
  version: "4.9.2"

  # Indexer configuration with external admin credentials
  indexer:
    replicas: 3
    storageSize: 50Gi
    javaOpts: "-Xms2g -Xmx2g -Dlog4j2.formatMsgNoLookups=true"
    resources:
      requests:
        cpu: 500m
        memory: 4Gi
      limits:
        cpu: 1
        memory: 4Gi
    service:
      type: ClusterIP

    # External credentials for the indexer admin user
    # If not specified, the operator auto-generates a random password
    credentials:
      secretName: indexer-admin-credentials
      usernameKey: username # optional, defaults to "username"
      passwordKey: password # optional, defaults to "password"

  # Manager configuration
  manager:
    master:
      storageSize: 10Gi
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
      service:
        type: ClusterIP
    workers:
      replicas: 1
      storageSize: 10Gi
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi

  # Dashboard configuration with credential reference
  dashboard:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 512Mi
    service:
      type: NodePort

    # Wazuh plugin configuration
    wazuhPlugin:
      enabled: true

      # Default API endpoint with credentials from secret
      # This is the simplest way to configure dashboard-to-manager authentication
      defaultApiEndpoint:
        credentialsSecret:
          secretName: wazuh-api-credentials
          usernameKey: username # optional, defaults to "username"
          passwordKey: password # optional, defaults to "password"
        port: 55000
        runAs: false

      pattern: "wazuh-alerts-*"
      timeout: 30000
      ipSelector: true
      hideManagerAlerts: false

  # TLS configuration
  tls:
    enabled: true
    certConfig:
      organization: "Wazuh Secure"
      country: "US"
      validityDays: 365

---
# 3. OPENSEARCH USERS - With password from secrets
# =================================================

# Default admin user - marked with defaultAdmin: true
# This user will be used as the cluster admin instead of auto-generated credentials
apiVersion: resources.wazuh.com/v1alpha1
kind: OpenSearchUser
metadata:
  name: admin
  namespace: wazuh
spec:
  clusterRef:
    name: wazuh-secure
    namespace: wazuh

  # Mark this user as the default admin for the cluster
  # Only one user per cluster should have this flag
  defaultAdmin: true

  # Password from the indexer admin secret
  passwordSecret:
    secretName: indexer-admin-credentials
    passwordKey: password # only passwordKey is used for OpenSearchUser

  # Admin gets all_access role
  openSearchRoles:
    - all_access

  description: "Cluster administrator"
---
# Security analyst user
apiVersion: resources.wazuh.com/v1alpha1
kind: OpenSearchUser
metadata:
  name: analyst
  namespace: wazuh
spec:
  clusterRef:
    name: wazuh-secure
    namespace: wazuh

  # Password from dedicated secret
  passwordSecret:
    secretName: analyst-user-password
    passwordKey: password # optional, defaults to "password"

  # Backend roles for LDAP/AD integration
  backendRoles:
    - analysts
    - security-team

  # OpenSearch security roles
  openSearchRoles:
    - readall
    - kibana_user
    - wazuh_analyst # Custom Wazuh role

  attributes:
    department: "Security Operations"
    team: "SOC"

  description: "Security analyst with read access to Wazuh alerts"
---
# Read-only user with custom password key
apiVersion: resources.wazuh.com/v1alpha1
kind: OpenSearchUser
metadata:
  name: readonly
  namespace: wazuh
spec:
  clusterRef:
    name: wazuh-secure
    namespace: wazuh

  # Password from secret with custom key
  passwordSecret:
    secretName: readonly-user-credentials
    passwordKey: user-password # using custom key

  openSearchRoles:
    - readall

  description: "Read-only user for reporting"
---
# User with pre-computed hash (alternative to password secret)
# Useful for migrating existing users or when you don't want to store the password
apiVersion: resources.wazuh.com/v1alpha1
kind: OpenSearchUser
metadata:
  name: legacy-user
  namespace: wazuh
spec:
  clusterRef:
    name: wazuh-secure
    namespace: wazuh

  # Pre-computed bcrypt hash (generated with: htpasswd -bnBC 12 "" password | tr -d ':\n')
  # This is an alternative to using passwordSecret
  hash: "$2y$12$abcdefghijklmnopqrstuv" # Replace with actual hash

  openSearchRoles:
    - kibana_user

  description: "Legacy user migrated with existing password hash"
