/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package config

import (
	"fmt"
	"strings"

	v1 "github.com/MaximeWewer/wazuh-operator/api/v1"
	"github.com/MaximeWewer/wazuh-operator/internal/utils"
	"github.com/MaximeWewer/wazuh-operator/pkg/constants"
)

// ============================================================================
// Dashboard Config Builder
// ============================================================================

// DashboardAuthConfigBuilder builds opensearch_dashboards.yml authentication settings
type DashboardAuthConfigBuilder struct {
	authConfig      *v1.OpenSearchAuthConfigSpec
	resolvedSecrets map[string]string
	serverHost      string
	serverPort      int
	opensearchURL   string
}

// NewDashboardAuthConfigBuilder creates a new DashboardAuthConfigBuilder
func NewDashboardAuthConfigBuilder(spec *v1.OpenSearchAuthConfigSpec) *DashboardAuthConfigBuilder {
	return &DashboardAuthConfigBuilder{
		authConfig:      spec,
		resolvedSecrets: make(map[string]string),
		serverHost:      "0.0.0.0",
		serverPort:      int(constants.PortDashboardHTTP),
		opensearchURL:   fmt.Sprintf("https://localhost:%d", constants.PortIndexerREST),
	}
}

// WithSecret adds a resolved secret value
func (b *DashboardAuthConfigBuilder) WithSecret(key, value string) *DashboardAuthConfigBuilder {
	b.resolvedSecrets[key] = value
	return b
}

// WithServerHost sets the dashboard server host
func (b *DashboardAuthConfigBuilder) WithServerHost(host string) *DashboardAuthConfigBuilder {
	b.serverHost = host
	return b
}

// WithServerPort sets the dashboard server port
func (b *DashboardAuthConfigBuilder) WithServerPort(port int) *DashboardAuthConfigBuilder {
	b.serverPort = port
	return b
}

// WithOpenSearchURL sets the OpenSearch backend URL
func (b *DashboardAuthConfigBuilder) WithOpenSearchURL(url string) *DashboardAuthConfigBuilder {
	b.opensearchURL = url
	return b
}

// BuildAuthSection generates the authentication section of opensearch_dashboards.yml
func (b *DashboardAuthConfigBuilder) BuildAuthSection() (string, error) {
	var sb strings.Builder

	sb.WriteString("# Security Plugin Configuration\n")
	sb.WriteString("# Generated by Wazuh Operator\n\n")

	// Determine auth type. When only one auth method is enabled, emit the scalar
	// form here. Multi-auth emits its own `opensearch_security.auth.type: [...]`
	// list in buildMultiAuthConfig, so writing a second (quoted) copy here would
	// produce a duplicate mapping key and break opensearch_dashboards.yml parsing.
	if !b.isMultiAuthEnabled() {
		fmt.Fprintf(&sb, "opensearch_security.auth.type: \"%s\"\n", b.determineAuthType())
	}

	// Build auth-specific configuration
	if b.authConfig.OIDC != nil && b.authConfig.OIDC.Enabled {
		oidcConfig, err := b.buildOIDCDashboardConfig()
		if err != nil {
			return "", fmt.Errorf("failed to build OIDC dashboard config: %w", err)
		}
		sb.WriteString(oidcConfig)
	}

	if b.authConfig.SAML != nil && b.authConfig.SAML.Enabled {
		sb.WriteString(b.buildSAMLDashboardConfig())
	}

	// Global session cookie password. Required whenever the dashboard serves
	// session-based auth flows (OIDC, SAML) so that signed cookies survive
	// dashboard restarts and are accepted across replicas.
	if (b.authConfig.OIDC != nil && b.authConfig.OIDC.Enabled) ||
		(b.authConfig.SAML != nil && b.authConfig.SAML.Enabled) {
		cookie, err := b.buildCookiePassword()
		if err != nil {
			return "", err
		}
		sb.WriteString(cookie)
	}

	// Multi-auth configuration
	if b.isMultiAuthEnabled() {
		sb.WriteString(b.buildMultiAuthConfig())
	}

	return sb.String(), nil
}

// determineAuthType returns the primary auth type for dashboard
func (b *DashboardAuthConfigBuilder) determineAuthType() string {
	// Count enabled auth types
	types := []string{}

	if b.authConfig.BasicAuth != nil && b.authConfig.BasicAuth.Enabled {
		types = append(types, "basicauth")
	}
	if b.authConfig.OIDC != nil && b.authConfig.OIDC.Enabled {
		types = append(types, "openid")
	}
	if b.authConfig.SAML != nil && b.authConfig.SAML.Enabled {
		types = append(types, "saml")
	}

	// Single type
	if len(types) == 1 {
		return types[0]
	}

	// Multiple types - use array format
	if len(types) > 1 {
		return fmt.Sprintf("[%s]", strings.Join(types, ", "))
	}

	// Default to basic auth
	return "basicauth"
}

// isMultiAuthEnabled returns true if multiple auth types are enabled
func (b *DashboardAuthConfigBuilder) isMultiAuthEnabled() bool {
	count := 0
	if b.authConfig.BasicAuth != nil && b.authConfig.BasicAuth.Enabled {
		count++
	}
	if b.authConfig.OIDC != nil && b.authConfig.OIDC.Enabled {
		count++
	}
	if b.authConfig.SAML != nil && b.authConfig.SAML.Enabled {
		count++
	}
	return count > 1
}

// ============================================================================
// OIDC Dashboard Config
// ============================================================================

// buildOIDCDashboardConfig generates OIDC-specific dashboard configuration.
// Reference: https://docs.opensearch.org/2.18/security/authentication-backends/openid-connect/
// Only keys documented for opensearch_dashboards.yml are emitted here. Prior
// versions emitted `openid.root_url`, `openid.login_endpoint`, `openid.logout_endpoint`,
// `openid.cookie.password` and `cookie.prefix` — none of those are recognized by
// opensearch-dashboards and they caused validation failures (FATAL ValidationError
// on "definition for this key is missing"). Cookie signing is now written under
// the global `opensearch_security.cookie.password` key by buildCookiePassword().
func (b *DashboardAuthConfigBuilder) buildOIDCDashboardConfig() (string, error) {
	var sb strings.Builder
	spec := b.authConfig.OIDC

	sb.WriteString("\n# OpenID Connect Configuration\n")

	fmt.Fprintf(&sb, "opensearch_security.openid.connect_url: \"%s\"\n", spec.ConnectURL)
	fmt.Fprintf(&sb, "opensearch_security.openid.client_id: \"%s\"\n", spec.ClientID)

	if secret, ok := b.resolvedSecrets["oidc_client_secret"]; ok && secret != "" {
		fmt.Fprintf(&sb, "opensearch_security.openid.client_secret: \"%s\"\n", secret)
	}
	if spec.Scope != "" {
		fmt.Fprintf(&sb, "opensearch_security.openid.scope: \"%s\"\n", spec.Scope)
	}
	if spec.LogoutURL != "" {
		fmt.Fprintf(&sb, "opensearch_security.openid.logout_url: \"%s\"\n", spec.LogoutURL)
	}

	if spec.Dashboard != nil {
		// CRD field RootURL maps to the documented base_redirect_url setting.
		if spec.Dashboard.RootURL != "" {
			fmt.Fprintf(&sb, "opensearch_security.openid.base_redirect_url: \"%s\"\n", spec.Dashboard.RootURL)
		}

		if len(spec.Dashboard.AdditionalCookies) > 0 {
			sb.WriteString("opensearch_security.openid.extra_storage.cookie_prefix: security_authentication_oidc\n")
			fmt.Fprintf(&sb, "opensearch_security.openid.extra_storage.additional_cookies: %d\n", len(spec.Dashboard.AdditionalCookies))
		}
	}

	return sb.String(), nil
}

// buildCookiePassword emits the global `opensearch_security.cookie.password`
// setting used by opensearch-dashboards to sign session cookies. It must be
// stable across reconciles (and across replicas) otherwise users are logged out
// on every dashboard restart and sessions break under multi-replica deployments.
// The caller must have injected a persisted value under `oidc_cookie_password`
// (reused here since cookie signing is shared across auth backends); if absent
// we still emit a random value so the plugin has something to sign with.
func (b *DashboardAuthConfigBuilder) buildCookiePassword() (string, error) {
	if secret, ok := b.resolvedSecrets["oidc_cookie_password"]; ok && secret != "" {
		return fmt.Sprintf("opensearch_security.cookie.password: \"%s\"\n", secret), nil
	}
	pwd, err := utils.GenerateRandomPassword(32)
	if err != nil {
		return "", fmt.Errorf("failed to generate dashboard cookie password: %w", err)
	}
	return fmt.Sprintf("opensearch_security.cookie.password: \"%s\"\n", pwd), nil
}

// ============================================================================
// SAML Dashboard Config
// ============================================================================

// buildSAMLDashboardConfig generates SAML-specific dashboard configuration.
// Reference: https://docs.opensearch.org/2.18/security/authentication-backends/saml/
// Only keys documented for opensearch_dashboards.yml are emitted. `saml.exchange_key`
// and `saml.requestedAuthnContextRef` belong to the security backend config.yml
// (http_authenticator.config.*) and are emitted there by the indexer security
// builder — writing them to opensearch_dashboards.yml produced ValidationErrors.
// The `server.xsrf.allowlist` entry is a core dashboards setting and remains valid.
func (b *DashboardAuthConfigBuilder) buildSAMLDashboardConfig() string {
	var sb strings.Builder
	spec := b.authConfig.SAML

	sb.WriteString("\n# SAML Configuration\n")

	var allowlist []string
	if spec.Dashboard != nil && len(spec.Dashboard.XSRFAllowlist) > 0 {
		allowlist = spec.Dashboard.XSRFAllowlist
	} else {
		allowlist = []string{
			"/_opendistro/_security/saml/acs",
			"/_opendistro/_security/saml/acs/idpinitiated",
			"/_opendistro/_security/saml/logout",
		}
	}
	sb.WriteString("server.xsrf.allowlist:\n")
	for _, path := range allowlist {
		fmt.Fprintf(&sb, "  - \"%s\"\n", path)
	}

	return sb.String()
}

// ============================================================================
// Multi-Auth Dashboard Config
// ============================================================================

// buildMultiAuthConfig generates multi-authentication configuration
func (b *DashboardAuthConfigBuilder) buildMultiAuthConfig() string {
	var sb strings.Builder

	sb.WriteString("\n# Multi-Auth Configuration\n")

	// Enable multiple authentication types
	sb.WriteString("opensearch_security.auth.multiple_auth_enabled: true\n")

	// Build ordered list of auth types
	type authMethod struct {
		name  string
		order int
	}

	var methods []authMethod

	if b.authConfig.BasicAuth != nil && b.authConfig.BasicAuth.Enabled {
		methods = append(methods, authMethod{"basicauth", b.authConfig.BasicAuth.Order})
	}
	if b.authConfig.OIDC != nil && b.authConfig.OIDC.Enabled {
		methods = append(methods, authMethod{"openid", b.authConfig.OIDC.Order})
	}
	if b.authConfig.SAML != nil && b.authConfig.SAML.Enabled {
		methods = append(methods, authMethod{"saml", b.authConfig.SAML.Order})
	}

	// Sort by order
	for i := 0; i < len(methods)-1; i++ {
		for j := i + 1; j < len(methods); j++ {
			if methods[j].order < methods[i].order {
				methods[i], methods[j] = methods[j], methods[i]
			}
		}
	}

	// Output auth types in order
	if len(methods) > 0 {
		types := make([]string, len(methods))
		for i, m := range methods {
			types[i] = fmt.Sprintf("\"%s\"", m.name)
		}
		fmt.Fprintf(&sb, "opensearch_security.auth.type: [%s]\n", strings.Join(types, ", "))
	}

	// Anonymous auth disable
	sb.WriteString("opensearch_security.auth.anonymous_auth_enabled: false\n")

	return sb.String()
}

// GetActiveAuthTypes returns a list of enabled dashboard auth types
func (b *DashboardAuthConfigBuilder) GetActiveAuthTypes() []string {
	var types []string

	if b.authConfig.BasicAuth != nil && b.authConfig.BasicAuth.Enabled {
		types = append(types, "basicauth")
	}
	if b.authConfig.OIDC != nil && b.authConfig.OIDC.Enabled {
		types = append(types, "openid")
	}
	if b.authConfig.SAML != nil && b.authConfig.SAML.Enabled {
		types = append(types, "saml")
	}

	return types
}

// NeedsDashboardRestart returns true if auth config changes require dashboard restart
func (b *DashboardAuthConfigBuilder) NeedsDashboardRestart(previous *v1.OpenSearchAuthConfigSpec) bool {
	if previous == nil {
		return true
	}

	// Check if auth types changed
	prevOIDC := previous.OIDC != nil && previous.OIDC.Enabled
	currOIDC := b.authConfig.OIDC != nil && b.authConfig.OIDC.Enabled
	if prevOIDC != currOIDC {
		return true
	}

	prevSAML := previous.SAML != nil && previous.SAML.Enabled
	currSAML := b.authConfig.SAML != nil && b.authConfig.SAML.Enabled
	if prevSAML != currSAML {
		return true
	}

	// Check if OIDC connect URL changed
	if currOIDC && previous.OIDC != nil {
		if b.authConfig.OIDC.ConnectURL != previous.OIDC.ConnectURL {
			return true
		}
		if b.authConfig.OIDC.ClientID != previous.OIDC.ClientID {
			return true
		}
	}

	// Check if SAML config changed
	if currSAML && previous.SAML != nil {
		if b.authConfig.SAML.IdpMetadataURL != previous.SAML.IdpMetadataURL {
			return true
		}
		if b.authConfig.SAML.IdpEntityID != previous.SAML.IdpEntityID {
			return true
		}
	}

	return false
}
