/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package config

import (
	"fmt"
	"strings"

	"github.com/MaximeWewer/wazuh-operator/pkg/constants"
)

// InternalUser represents an OpenSearch internal user
type InternalUser struct {
	// Username is the user identifier
	Username string
	// Hash is the bcrypt password hash
	Hash string
	// Reserved marks the user as reserved (cannot be modified via API)
	Reserved bool
	// Hidden hides the user from API responses
	Hidden bool
	// BackendRoles are the backend roles assigned to this user
	BackendRoles []string
	// Description is a human-readable description
	Description string
	// Attributes are custom attributes for the user
	Attributes map[string]string
}

// InternalUsersConfig holds the configuration for internal_users.yml
type InternalUsersConfig struct {
	Users []InternalUser
}

// DefaultInternalUsersConfig returns a default internal users configuration
// with standard Wazuh/OpenSearch users
func DefaultInternalUsersConfig() *InternalUsersConfig {
	return &InternalUsersConfig{
		Users: []InternalUser{
			{
				Username:     constants.DefaultOpenSearchAdminUsername,
				Hash:         "$2y$12$K/SpwjtB.wOHJ/Nc6GVRDuc1h0rM1DfvziFRNPtk27P.c4yDr9njO", // admin
				Reserved:     true,
				BackendRoles: []string{constants.DefaultOpenSearchAdminUsername},
				Description:  "Admin user",
			},
			{
				Username:    constants.DefaultKibanaServerUsername,
				Hash:        "$2y$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H.", // kibanaserver
				Reserved:    true,
				Hidden:      false,
				Description: "Dashboard server user",
			},
			{
				Username:     "kibanaro",
				Hash:         "$2y$12$JJSXNfTowz7Uu5ttXfeYpeYE0arACvcwlPBStB1F.MI7f0U9Z4DGC", // kibanaro
				Reserved:     false,
				BackendRoles: []string{"kibanauser", "readall"},
				Description:  "Dashboard read-only user",
				Attributes: map[string]string{
					"attribute1": "value1",
				},
			},
			{
				Username:     "logstash",
				Hash:         "$2y$12$u1ShR4l4uBS3Uv59Pa2y5.1uQuZBrZtmNfqB3iM/.jL0XoV9sghS2", // logstash
				Reserved:     false,
				BackendRoles: []string{"logstash"},
				Description:  "Logstash user",
			},
			{
				Username:     "readall",
				Hash:         "$2y$12$ae4ycwzwvLtZxwZ82RmiEunBbIPiAmGZduBAjKN0TXdwQFtCwARz2", // readall
				Reserved:     false,
				BackendRoles: []string{"readall"},
				Description:  "Read-all user",
			},
			{
				Username:     "snapshotrestore",
				Hash:         "$2y$12$DpwmetHKwgYnorbgdvORCenv4NAK8cPUg8AI6pxLCuWf/ALc0.v7W", // snapshotrestore
				Reserved:     false,
				BackendRoles: []string{"snapshotrestore"},
				Description:  "Snapshot/restore user",
			},
		},
	}
}

// NewInternalUsersConfig creates a new empty InternalUsersConfig
func NewInternalUsersConfig() *InternalUsersConfig {
	return &InternalUsersConfig{
		Users: make([]InternalUser, 0),
	}
}

// AddUser adds a user to the configuration
func (c *InternalUsersConfig) AddUser(user InternalUser) *InternalUsersConfig {
	c.Users = append(c.Users, user)
	return c
}

// SetAdminHash sets the admin user's password hash
func (c *InternalUsersConfig) SetAdminHash(hash string) *InternalUsersConfig {
	for i, user := range c.Users {
		if user.Username == constants.DefaultOpenSearchAdminUsername {
			c.Users[i].Hash = hash
			return c
		}
	}
	// If admin user doesn't exist, add it
	c.Users = append(c.Users, InternalUser{
		Username:     constants.DefaultOpenSearchAdminUsername,
		Hash:         hash,
		Reserved:     true,
		BackendRoles: []string{constants.DefaultOpenSearchAdminUsername},
		Description:  "Admin user",
	})
	return c
}

// SetKibanaServerHash sets the kibanaserver user's password hash
func (c *InternalUsersConfig) SetKibanaServerHash(hash string) *InternalUsersConfig {
	for i, user := range c.Users {
		if user.Username == constants.DefaultKibanaServerUsername {
			c.Users[i].Hash = hash
			return c
		}
	}
	return c
}

// Build generates the internal_users.yml content
func (c *InternalUsersConfig) Build() string {
	var sb strings.Builder

	sb.WriteString("# OpenSearch Internal Users Configuration\n")
	sb.WriteString("# Generated by Wazuh Operator\n")
	sb.WriteString("---\n")
	sb.WriteString("_meta:\n")
	sb.WriteString("  type: \"internalusers\"\n")
	sb.WriteString("  config_version: 2\n\n")

	for _, user := range c.Users {
		sb.WriteString(fmt.Sprintf("%s:\n", user.Username))
		sb.WriteString(fmt.Sprintf("  hash: \"%s\"\n", user.Hash))

		if user.Reserved {
			sb.WriteString("  reserved: true\n")
		}

		if user.Hidden {
			sb.WriteString("  hidden: true\n")
		}

		if len(user.BackendRoles) > 0 {
			sb.WriteString("  backend_roles:\n")
			for _, role := range user.BackendRoles {
				sb.WriteString(fmt.Sprintf("    - \"%s\"\n", role))
			}
		}

		if user.Description != "" {
			sb.WriteString(fmt.Sprintf("  description: \"%s\"\n", user.Description))
		}

		if len(user.Attributes) > 0 {
			sb.WriteString("  attributes:\n")
			for k, v := range user.Attributes {
				sb.WriteString(fmt.Sprintf("    %s: \"%s\"\n", k, v))
			}
		}

		sb.WriteString("\n")
	}

	return sb.String()
}

// BuildInternalUsers is a convenience function to build internal_users.yml
func BuildInternalUsers(adminHash, kibanaServerHash string) string {
	config := DefaultInternalUsersConfig()
	if adminHash != "" {
		config.SetAdminHash(adminHash)
	}
	if kibanaServerHash != "" {
		config.SetKibanaServerHash(kibanaServerHash)
	}
	return config.Build()
}
