/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package config

import (
	"fmt"
	"strings"

	"github.com/MaximeWewer/wazuh-operator/internal/certificates"
)

// RoleMapping represents an OpenSearch role mapping
type RoleMapping struct {
	// RoleName is the role to map to
	RoleName string
	// Reserved marks the mapping as reserved
	Reserved bool
	// Hidden hides the mapping from API responses
	Hidden bool
	// Description is a human-readable description
	Description string
	// BackendRoles are the backend roles to map
	BackendRoles []string
	// Hosts are the hosts to map
	Hosts []string
	// Users are the users to map
	Users []string
	// AndBackendRoles requires all backend roles to match (AND logic)
	AndBackendRoles []string
}

// RolesMappingConfig holds the configuration for roles_mapping.yml
type RolesMappingConfig struct {
	Mappings []RoleMapping
}

// DefaultRolesMappingConfig returns a default roles mapping configuration
func DefaultRolesMappingConfig() *RolesMappingConfig {
	return DefaultRolesMappingConfigWithAdminDN(certificates.DefaultAdminDN())
}

// DefaultRolesMappingConfigWithAdminDN returns a default roles mapping configuration with custom admin DN
func DefaultRolesMappingConfigWithAdminDN(adminDN string) *RolesMappingConfig {
	return &RolesMappingConfig{
		Mappings: []RoleMapping{
			{
				RoleName:     "all_access",
				Reserved:     false,
				Hidden:       false,
				Description:  "Map admin backend role and admin certificate to all_access",
				BackendRoles: []string{"admin"},
				// Also map the admin certificate DN to all_access for certificate-based auth
				// This is required for the certificate reload API to work
				Users: []string{adminDN},
			},
			{
				RoleName:    "own_index",
				Reserved:    false,
				Hidden:      false,
				Description: "Map users to their own index",
				Users:       []string{"*"},
			},
			{
				RoleName:     "readall",
				Reserved:     false,
				Hidden:       false,
				Description:  "Map readall backend role",
				BackendRoles: []string{"readall"},
			},
			{
				RoleName:     "kibana_user",
				Reserved:     false,
				Hidden:       false,
				Description:  "Map kibanauser backend role",
				BackendRoles: []string{"kibanauser"},
			},
			{
				RoleName:    "kibana_server",
				Reserved:    true,
				Hidden:      false,
				Description: "Map kibanaserver user to kibana_server role",
				Users:       []string{"kibanaserver"},
			},
			// Wazuh specific mappings
			{
				RoleName:     "wazuh_admin",
				Reserved:     false,
				Hidden:       false,
				Description:  "Map wazuh_admin backend role",
				BackendRoles: []string{"wazuh_admin"},
			},
			{
				RoleName:     "wazuh_user",
				Reserved:     false,
				Hidden:       false,
				Description:  "Map wazuh_user backend role",
				BackendRoles: []string{"wazuh_user"},
			},
		},
	}
}

// NewRolesMappingConfig creates a new empty RolesMappingConfig
func NewRolesMappingConfig() *RolesMappingConfig {
	return &RolesMappingConfig{
		Mappings: make([]RoleMapping, 0),
	}
}

// AddMapping adds a mapping to the configuration
func (c *RolesMappingConfig) AddMapping(mapping RoleMapping) *RolesMappingConfig {
	c.Mappings = append(c.Mappings, mapping)
	return c
}

// Build generates the roles_mapping.yml content
func (c *RolesMappingConfig) Build() string {
	var sb strings.Builder

	sb.WriteString("# OpenSearch Roles Mapping Configuration\n")
	sb.WriteString("# Generated by Wazuh Operator\n")
	sb.WriteString("---\n")
	sb.WriteString("_meta:\n")
	sb.WriteString("  type: \"rolesmapping\"\n")
	sb.WriteString("  config_version: 2\n\n")

	for _, mapping := range c.Mappings {
		sb.WriteString(fmt.Sprintf("%s:\n", mapping.RoleName))

		if mapping.Reserved {
			sb.WriteString("  reserved: true\n")
		}

		if mapping.Hidden {
			sb.WriteString("  hidden: true\n")
		}

		if mapping.Description != "" {
			sb.WriteString(fmt.Sprintf("  description: \"%s\"\n", mapping.Description))
		}

		if len(mapping.BackendRoles) > 0 {
			sb.WriteString("  backend_roles:\n")
			for _, role := range mapping.BackendRoles {
				sb.WriteString(fmt.Sprintf("    - \"%s\"\n", role))
			}
		}

		if len(mapping.Hosts) > 0 {
			sb.WriteString("  hosts:\n")
			for _, host := range mapping.Hosts {
				sb.WriteString(fmt.Sprintf("    - \"%s\"\n", host))
			}
		}

		if len(mapping.Users) > 0 {
			sb.WriteString("  users:\n")
			for _, user := range mapping.Users {
				sb.WriteString(fmt.Sprintf("    - \"%s\"\n", user))
			}
		}

		if len(mapping.AndBackendRoles) > 0 {
			sb.WriteString("  and_backend_roles:\n")
			for _, role := range mapping.AndBackendRoles {
				sb.WriteString(fmt.Sprintf("    - \"%s\"\n", role))
			}
		}

		sb.WriteString("\n")
	}

	return sb.String()
}

// BuildRolesMapping is a convenience function to build default roles_mapping.yml
func BuildRolesMapping() string {
	return DefaultRolesMappingConfig().Build()
}
