/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package config

import (
	"strings"
)

// AuthDomain represents an authentication domain configuration
type AuthDomain struct {
	// Name is the domain identifier
	Name string
	// HTTPEnabled enables HTTP authentication
	HTTPEnabled bool
	// TransportEnabled enables transport authentication
	TransportEnabled bool
	// Order is the evaluation order
	Order int
	// HTTPAuthenticator defines the HTTP authenticator
	HTTPAuthenticator *HTTPAuthenticator
	// AuthenticationBackend defines the authentication backend
	AuthenticationBackend *AuthenticationBackend
	// Description is a human-readable description
	Description string
}

// HTTPAuthenticator defines HTTP authentication settings
type HTTPAuthenticator struct {
	// Type is the authenticator type (e.g., "basic", "proxy", "jwt")
	Type string
	// Challenge enables WWW-Authenticate challenge
	Challenge bool
	// Config holds additional configuration
	Config map[string]interface{}
}

// AuthenticationBackend defines the authentication backend
type AuthenticationBackend struct {
	// Type is the backend type (e.g., "internal", "ldap", "noop")
	Type string
	// Config holds additional configuration
	Config map[string]interface{}
}

// SecurityPluginConfig holds the configuration for config.yml (security plugin)
type SecurityPluginConfig struct {
	// Dynamic holds dynamic configuration
	Dynamic *DynamicConfig
}

// DynamicConfig holds dynamic security configuration
type DynamicConfig struct {
	// HTTPEnabled enables HTTP layer security
	HTTPEnabled bool
	// HTTPAnonymousAuthEnabled enables anonymous authentication
	HTTPAnonymousAuthEnabled bool
	// AuthDomains are the authentication domains
	AuthDomains []AuthDomain
	// DoNotFailOnForbidden controls 403 behavior
	DoNotFailOnForbidden bool
	// DoNotFailOnForbiddenEmpty controls empty response behavior
	DoNotFailOnForbiddenEmpty bool
	// RespectRequestIndicesOptions respects request index options
	RespectRequestIndicesOptions bool
	// MultiRolesFilterEnabled enables multi-role filtering
	MultiRolesFilterEnabled bool
}

// DefaultSecurityPluginConfig returns a default security plugin configuration
func DefaultSecurityPluginConfig() *SecurityPluginConfig {
	return &SecurityPluginConfig{
		Dynamic: &DynamicConfig{
			HTTPEnabled:              true,
			HTTPAnonymousAuthEnabled: false,
			AuthDomains: []AuthDomain{
				{
					Name:             "basic_internal_auth_domain",
					HTTPEnabled:      true,
					TransportEnabled: true,
					Order:            0,
					HTTPAuthenticator: &HTTPAuthenticator{
						Type:      "basic",
						Challenge: true,
					},
					AuthenticationBackend: &AuthenticationBackend{
						Type: "internal",
					},
					Description: "Authenticate via HTTP Basic against internal users database",
				},
			},
			DoNotFailOnForbidden:         false,
			DoNotFailOnForbiddenEmpty:    false,
			RespectRequestIndicesOptions: true,
			MultiRolesFilterEnabled:      true,
		},
	}
}

// NewSecurityPluginConfig creates a new SecurityPluginConfig with defaults
func NewSecurityPluginConfig() *SecurityPluginConfig {
	return DefaultSecurityPluginConfig()
}

// AddAuthDomain adds an authentication domain
func (c *SecurityPluginConfig) AddAuthDomain(domain AuthDomain) *SecurityPluginConfig {
	c.Dynamic.AuthDomains = append(c.Dynamic.AuthDomains, domain)
	return c
}

// EnableAnonymousAuth enables anonymous authentication
func (c *SecurityPluginConfig) EnableAnonymousAuth() *SecurityPluginConfig {
	c.Dynamic.HTTPAnonymousAuthEnabled = true
	return c
}

// Build generates the config.yml content
func (c *SecurityPluginConfig) Build() string {
	var sb strings.Builder

	sb.WriteString("# OpenSearch Security Plugin Configuration\n")
	sb.WriteString("# Generated by Wazuh Operator\n")
	sb.WriteString("---\n")
	sb.WriteString("_meta:\n")
	sb.WriteString("  type: \"config\"\n")
	sb.WriteString("  config_version: 2\n\n")

	sb.WriteString("config:\n")
	sb.WriteString("  dynamic:\n")

	// HTTP settings
	if c.Dynamic.HTTPEnabled {
		sb.WriteString("    http:\n")
		sb.WriteString("      anonymous_auth_enabled: ")
		if c.Dynamic.HTTPAnonymousAuthEnabled {
			sb.WriteString("true\n")
		} else {
			sb.WriteString("false\n")
		}
	}

	// Authentication domains
	if len(c.Dynamic.AuthDomains) > 0 {
		sb.WriteString("    authc:\n")
		for _, domain := range c.Dynamic.AuthDomains {
			sb.WriteString("      " + domain.Name + ":\n")
			if domain.Description != "" {
				sb.WriteString("        description: \"" + domain.Description + "\"\n")
			}
			sb.WriteString("        http_enabled: ")
			if domain.HTTPEnabled {
				sb.WriteString("true\n")
			} else {
				sb.WriteString("false\n")
			}
			sb.WriteString("        transport_enabled: ")
			if domain.TransportEnabled {
				sb.WriteString("true\n")
			} else {
				sb.WriteString("false\n")
			}

			if domain.HTTPAuthenticator != nil {
				sb.WriteString("        http_authenticator:\n")
				sb.WriteString("          type: \"" + domain.HTTPAuthenticator.Type + "\"\n")
				sb.WriteString("          challenge: ")
				if domain.HTTPAuthenticator.Challenge {
					sb.WriteString("true\n")
				} else {
					sb.WriteString("false\n")
				}
			}

			if domain.AuthenticationBackend != nil {
				sb.WriteString("        authentication_backend:\n")
				sb.WriteString("          type: \"" + domain.AuthenticationBackend.Type + "\"\n")
			}
		}
	}

	// Additional settings
	sb.WriteString("    do_not_fail_on_forbidden: ")
	if c.Dynamic.DoNotFailOnForbidden {
		sb.WriteString("true\n")
	} else {
		sb.WriteString("false\n")
	}

	sb.WriteString("    do_not_fail_on_forbidden_empty: ")
	if c.Dynamic.DoNotFailOnForbiddenEmpty {
		sb.WriteString("true\n")
	} else {
		sb.WriteString("false\n")
	}

	sb.WriteString("    multi_rolespan_enabled: ")
	if c.Dynamic.MultiRolesFilterEnabled {
		sb.WriteString("true\n")
	} else {
		sb.WriteString("false\n")
	}

	sb.WriteString("    respect_request_indices_options: ")
	if c.Dynamic.RespectRequestIndicesOptions {
		sb.WriteString("true\n")
	} else {
		sb.WriteString("false\n")
	}

	return sb.String()
}

// BuildSecurityConfig is a convenience function to build default config.yml
func BuildSecurityConfig() string {
	return DefaultSecurityPluginConfig().Build()
}
