# Minimal WazuhCluster - Quick Start Example
#
# This example deploys a minimal Wazuh cluster suitable for:
# - Development and testing
# - Learning the operator
# - Resource-constrained environments (4 vCPU, 6GB RAM)
#
# Usage:
#   kubectl create namespace wazuh
#   kubectl apply -f 01-minimal-cluster.yaml
#
apiVersion: resources.wazuh.com/v1alpha1
kind: WazuhCluster
metadata:
  name: wazuh-quickstart
  namespace: wazuh
  labels:
    environment: development
spec:
  # Wazuh version - see https://documentation.wazuh.com for available versions
  version: "4.9.0"

  # Indexer configuration (OpenSearch-based)
  indexer:
    replicas: 1
    storageSize: 10Gi
    javaOpts: "-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        cpu: 1
        memory: 2Gi
    service:
      type: ClusterIP

  # Manager configuration
  manager:
    master:
      storageSize: 5Gi
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
      service:
        type: ClusterIP
    workers:
      replicas: 0  # No workers for minimal setup

  # Dashboard configuration
  dashboard:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 512Mi
    service:
      type: NodePort  # Easy access on minikube/kind

  # TLS enabled by default
  tls:
    enabled: true
    certConfig:
      organization: "Wazuh Quick Start"
      country: "US"
